### ISSUE TITLE
[Bug]: 无法加载非H系模组的图片

### ISSUE THREAD

**Issue by QingFeng-awa** [QingFeng-awa/AuModSite#11]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的问题，没有找到相同问题的issue。
- [X] 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。

### 出现问题的URL

https://aumod.site/Mods/NoHost/{ModName}

### 遇到/发现了什么问题?

受DDoS攻击影响,提供CDN服务的对象存储现无法访问。
这就导致了本站的所有图片都无法加载。
尽管第一时间我们做出了修正,但仍有部分图片未更改。

### 其它信息

非H系就2模组,乐崽pr能给修了吗）

**Comment by QingFeng-awa** [comment]
@LezaiYa1

**Comment by LezaiYa1** [comment]
等一下我看看吧，我还在写TONEX的EAC

**Comment by QingFeng-awa** [comment]
> 等一下我看看吧，我还在写TONEX的EAC

没事,慢慢写,不着急）
