### ISSUE TITLE
[Opt]: 修正TownOfNewEpic_Xtreme

### ISSUE THREAD

**Issue by QingFeng-awa** [QingFeng-awa/AuModSite#15]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的问题，没有找到相同问题的issue。
- [X] 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。

### 请求优化的URL

https://aumod.site/Mods/Host/TownOfNewEpic_Xtreme

### 请求优化的功能

WHO 回退了 TONEX 的修改?

**Comment by LezaiYa1** [comment]
https://github.com/QingFeng-awa/AuModSite/pull/14/commits/73cf3bb11bf65981b9061d2a33bd929c1eff019b
你可以照着这个commit改

**Comment by QingFeng-awa** [comment]
> [73cf3bb](https://github.com/QingFeng-awa/AuModSite/commit/73cf3bb11bf65981b9061d2a33bd929c1eff019b) 你可以照着这个commit改

但是图片都removed了,我懒得整图片）
