### ISSUE TITLE
[Bug]: 关于捐赠

### ISSUE THREAD

**Issue by Slok7565** [QingFeng-awa/AuModSite#17]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的问题，没有找到相同问题的issue。
- [X] 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。

### 出现问题的URL

https://b23.tv/noy3XoZ

### 遇到/发现了什么问题?

为什么没有关于捐赠多少钱给我邮个清风过来的价目

### 期望正确结果是?

把清风邮过来，让他成为[[大人物]]！！

**Comment by QingFeng-awa** [comment]
神经病
