### ISSUE TITLE
[Opt]: 删除那些没有被使用的图片

### ISSUE THREAD

**Issue by QingFeng-awa** [QingFeng-awa/AuModSite#23]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的问题，没有找到相同问题的issue。
- [X] 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。

### 请求优化的URL

https://aumod.site/Image/

### 请求优化的功能

在最近几天的commit中,我将所有页面的作者信息改成了只保留一个,其余全部删除。
然而我并没有一起移除这些不再使用的图片,这就导致了`Image`文件夹的占用过高。
不仅对服务器端没什么好处,Git`clone`,GitHub Fork的时间也会更长。
这显然不是我想看到的。

**Comment by LezaiYa1** [comment]
只要网速够好，就能做到秒clone（（（
