### ISSUE TITLE
[Feat]: 增加模组分支

### ISSUE THREAD

**Issue by miaoice** [QingFeng-awa/AuModSite#5]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的功能请求，没有找到相同请求的issue。
- [X] 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。

### 请求增加的功能

增加显示各个模组之间的分支情况

### 其它信息

例如

- TOH
    - TOHEdited
        - TOHEnhanced

**Comment by QingFeng-awa** [comment]
未来考虑

**Comment by QingFeng-awa** [comment]
由于模组分支错综复杂,我没空去梳理分支树,所以
